addSbtPlugin("org.typelevel"             % "sbt-tpolecat"             % "0.5.1")
addSbtPlugin("io.spray"                  % "sbt-revolver"             % "0.10.0")
addSbtPlugin("com.github.sbt"            % "sbt-native-packager"      % "1.10.0")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"             % "0.12.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"             % "2.5.2")